### ISSUE TITLE
Build error when using Zodern relay plugin

### ISSUE THREAD

**Issue by timsun28** [JorgenVatle/meteor-vite#182]
When trying to build/deploy a project with the zodern relay plugin setup i'm getting the following error: 
```/tanstack-query-todo/.meteor/local/vite/bundle/meteor-entry.js: Cannot read properties of undefined (reading 'arch')```

This issue can be seen on the following repo: https://github.com/timsun28/tanstack-query-todo/tree/vite-bundler
If you try to run meteor build it will crash with the error.

When I looked for the arch property in the @zodern babel plugin I found this line of code:
```isServer = caller.arch.startsWith('os.');```

So it seems like it isn't able to find the caller but only in the bundled meteor-entry file. 

The only thing I can think of at the moment is that I'm running the zodern plugin from a local folder right now with the included typescript presets until it gets [merged](https://github.com/JorgenVatle/meteor-vite/pull/181) into this project. But I can't really confirm if this is the issue.

Update: 
I've found that removing the plugin from the .babelrc file fixes the issue, however I would now need to check in more detail if it still works as expected and doesn't ship any server side code to the client.

**Comment by JorgenVatle** [comment]
This should be fixed with [`jorgenvatle:vite-bundler@2.0.3`](https://atmospherejs.com/jorgenvatle/vite-bundler) and the latest version of [`@meteor-vite/plugin-zodern-relay`](https://npmjs.com/@meteor-vite/plugin-zodern-relay). Let me know how it goes. 👍

The Babel plugin for `zodern:relay` in `.babelrc` likely becomes redundant following this update as the plugin is automatically loaded by the Vite plugin [`@meteor-vite/plugin-zodern-relay`](https://npmjs.com/@meteor-vite/plugin-zodern-relay) when necessary.
