### ISSUE TITLE
Build issues on 2.2.0

### ISSUE THREAD

**Issue by dallman2** [JorgenVatle/meteor-vite#240]
Hey Jorgen,

As i mentioned in the other issue, this is whats happening when i try to build now.

### I think this means vite is trying to build the server and is succeeding
```
⚡  Meteor Server bundling with Vite is enabled. This is an experimental feature that will attempt to bundle your Meteor server using Vite.
CLI Building entry: server/meteor-entry.js
CLI Using tsconfig: tsconfig.json
CLI tsup v8.3.5
CLI Target: es2022
CJS Build start
CJS _vite-bundle/server/meteor-entry.js     3.66 MB
CJS _vite-bundle/server/meteor-entry.js.map 4.93 MB
CJS ⚡️ Build success in 443ms
⚡  Vite build completed in 13.61s
```

### I think this means that the build didn't work as intended, or we are trying to find `meteor-entry` in a place where it isn't
```
⚡   Failed to complete build process:
 MeteorViteError: ⚡  No meteor-entry chunk found
    at prepareViteBundle (packages/vite/src/plugin/IntermediaryMeteorProject.ts:167:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at build (packages/vite/src/build.ts:64:35)
Errors prevented bundling:                    
While running registerCompiler callback in package jorgenvatle:vite-bundler-local:
packages/vite/src/plugin/IntermediaryMeteorProject.ts:167:15: ⚡  No meteor-entry chunk found
at prepareViteBundle (packages/vite/src/plugin/IntermediaryMeteorProject.ts:167:15)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at build (packages/vite/src/build.ts:64:35)
```
I have checked other locations in the project after attempting the build, `_vite-bundle/server/meteor-entry.js` exists and looks like it contains what we want. Maybe I have my temp directories set up wrong?? Not sure.

**Comment by JorgenVatle** [comment]
For building the Meteor server with Vite, I would probably just recommend using the Meteor-Vite v3 pre-release packages. I found that building with Vite was decently fast for smaller apps, but would turn into a pretty big slowdown for larger apps in development mode as you would have to do a full build between server restarts.

So the only performance gain to be had would be for the one build you do when building for production. 

You could also just turn off the server builds, it shouldn't make any difference to your app unless you are specifically using server-rendering features. If anything it should work a little better during development.

---
- #173

Even though its marked as a pre-release, it should be more stable than the current stable releases. Instead of building with Vite, it will build the server with ESBuild. This does lose some compatibility with Vite plugins. But unless you have some fancy Vite config specifically for the server, this should work fine for most users.

---
- #235

Finally, there's Meteor-Vite v3.1 (or maybe v4), which doesn't have any published releases just yet. I'm shamelessly mentioning here because it is the fastest I've ever seen Meteor build, shockingly fast. All while removing more than half of this codebase persisting of hacks needed to support running Vite from Meteor. 

This is back to building the Meteor server with Vite, this time using Vite v6 which now has official support for non-standard environments. This means your Vite plugins should work as expected on the server. It's also easier to target just the server or client with certain config options specific to a given environment.

Vite v6 is still in alpha unfortunately.

**Comment by dallman2** [comment]
oh yes, about that. the `meteor add jorgenvatle:vite-bundler@3.0.0-meteor3-next.27` does not resolve to anything. I also cannot see the Packosphere page for your bundler anymore... its just blank

**Comment by JorgenVatle** [comment]
Oh yeah, not sure what's been going on with the Packosphere page. It's been like that for a few months now. 😂

**Comment by JorgenVatle** [comment]
Aha oops, there's a typo in the version tag.

`jorgenvatle:vite-bundler@3.0.0-meteor3.next.27` is the latest pre-release. Note the use of a dot instead of a dash.

**Comment by dallman2** [comment]
okay that version worked. now, with the experimental flag turned on, i was able to get the server to build as well. there were a few `ignores` that i had to do, as the vite config and meteor ignore files both need to be aware of the vite bundle folders to avoid an infinite build loop. finally, my `package.json` looks like this: 
```
...
  "meteor": {
    "mainModule": {
      "client": "client/main.js",
      "server": "server/main.js"
    },
    "vite": {
      "tempBuildDir": "../tempBuildDir"
    }
  },
...
```
my vite config looks like this: 
```
const viteConfig = defineViteConfig({
  plugins: [
    react({
      jsxRuntime: 'classic',
    }),
    meteor({
      clientEntry: 'imports/ui/vite-entrypoint.tsx',
      // clientEntry: 'imports/ui/meteor-entry.ts',
      serverEntry: 'server/meteor-entry.js',
      enableExperimentalFeatures: true,
      stubValidation: {
        warnOnly: true,
      },
      // meteorStubs: {
      //   debug: false,
      // },
    }),
]
...
  server: {
    hmr: true,
    watch: {
      // Ensure server-side files are watched
      ignored: [
        '_vite-bundle/**',
        '**/node_modules/**',
        '**/.meteor/**',
      ],
    },
  },
```
my `meteor-entry` for the client looks like this:
```
import '/imports/ui/vite-entrypoint'
```
and both of my `main.js` files just have the imports that bootstrap their respective areas.

**Comment by dallman2** [comment]
all of that is to say, i *think* i have it working, not totally sure yet, but i believe what i have above is the minimum boilerplate to get the bundler to do both the client and server as well as build properly

**Comment by JorgenVatle** [comment]
What a headache. 😅

Disregarding the server builds for a bit, it should just be a matter of dropping in Vite in place of your old client entrypoint. There shouldn't be more configuration necessary. For the server, it hasn't been tested that much yet so some issues are to be expected.  

As for the restart loop, it should only restart once or twice on first startup as it prepares your internal Vite entrypoints. If it continuously restarts, I suspect there could be a stray import somewhere.

Adding anything to either `.meteorignore` or Vite's ignored files should not be necessary. Specifically adding `_vite-bundle` to `.meteorignore` will likely cause some issues when you go to build the app. If it did let you build after doing this, I suspect it could be from the temporary files described below.

After upgrading from Meteor-Vite v2 to Meteor-Vite v3, there may be some stray files remaining from the old approach to preparing proxy modules for your app. I would make sure to remove any `_vite-bundle` directories created by Vite in either `/server/` and `/client/` respectively. The new root for these temporary files has been moved to the `_vite-bundle` directory at the root of your project.

**Comment by dallman2** [comment]
The crazy thing is it just built on github for me. As in, no cached files and no migration from v2. My deploy environment for this will be up tomorrow so I will be able to let you know if it actually works, but the config I described above ran in dev mode and built for production both locally and on the cloud...

Strange times indeed

Also, I am using the `2.0.0-next.8` version of the Meteor Vite npm package. Is that the one designed to go with v3 of the meteor package?

**Comment by JorgenVatle** [comment]
Ahah, in that case no harm no foul.

Yes, 2.0.0-next.* is for Meteor-Vite v3 👍

**Comment by dallman2** [comment]
Perfect. for now i will close this, if you hear nothing from me tomorrow it means that i could deploy and the current setup works!
